package cn.iaicc.smgk.web.conf;

import java.util.HashMap;


public class NationsConstants {

	//民族信息
	
	public static final int HANZU = 1;
	public static final int ZHUANGZU = 2;
	public static final int MANZU = 3;
	public static final int HUIZU = 4;
	public static final int MIAOZU = 5;
	public static final int WEIWUERZU = 6;
	public static final int YIZU = 7;
	public static final int TUJIAZU = 8;
	public static final int MENGGUZU = 9;
	public static final int ZANGZU = 10;
	public static final int BUYIZU = 11;
	public static final int DONGZU =12;
	public static final int YAOZU = 13;
	public static final int CHAOXIANZU = 14;
	public static final int BAIZU = 15;
	public static final int HANIZU = 16;
	public static final int LIZU = 17;
	public static final int HASAKEZU = 18;
	public static final int DAIZU = 19;
	public static final int SHEZU = 20;
	public static final int LISUZU = 21;
	public static final int GELAOZU = 22;
	public static final int LAHUZU = 23;
	public static final int DONGXIANGZU = 24;
	public static final int WAZU = 25;
	public static final int SHUIZU = 26;
	public static final int NAXIZU = 27;
	public static final int QIANGZU = 28;
	public static final int TUZU = 29;
	public static final int XIBOZU = 30;
	public static final int MULAOZU = 31;
	public static final int KEERKEZIZU = 32;
	public static final int DAWOERZU = 33;
	public static final int JINGPOZU = 34;
	public static final int SALAZU = 35;
	public static final int BULANGZU = 36;
	public static final int MAONANZU = 37;
	public static final int TAJIKEZU = 38;
	public static final int PUMIZU = 39;
	public static final int ACHANGZU = 40;
	public static final int NUZU = 41;
	public static final int EWENKEZU = 42;
	public static final int JINGZU = 43;
	public static final int JINUOZU = 44;
	public static final int DEANGZU = 45;
	public static final int WUZIBIEKEZU = 46;
	public static final int ELUOSIZU = 47;
	public static final int YUGUZU = 48;
	public static final int BAOANZU = 49;	
	public static final int MENBAZU = 50;
	public static final int ELUNCHUNZU = 51;
	public static final int DULONGZU = 52;
	public static final int TATAERZU = 53;	
	public static final int HEZHEZU = 54;
	public static final int LUOBAZU = 55;
	public static final int GAOSHANZU = 56;
	
	public static HashMap<Integer,Boolean> nation;
	public static HashMap<Integer,String> nationDict;
	
	static {
		nation = new HashMap<Integer,Boolean>();
		nationDict = new HashMap<Integer,String>();		
		
		nation.put(new Integer(HANZU), new Boolean(true));
		nation.put(new Integer(ZHUANGZU), new Boolean(true));
		nation.put(new Integer(MANZU), new Boolean(true));
		nation.put(new Integer(HUIZU), new Boolean(true));
		nation.put(new Integer(MIAOZU), new Boolean(true));
		nation.put(new Integer(WEIWUERZU), new Boolean(true));
		nation.put(new Integer(YIZU), new Boolean(true));
		nation.put(new Integer(TUJIAZU), new Boolean(true));
		nation.put(new Integer(MENGGUZU), new Boolean(true));
		nation.put(new Integer(ZANGZU), new Boolean(true));
		nation.put(new Integer(BUYIZU), new Boolean(true));
		nation.put(new Integer(DONGZU), new Boolean(true));
		nation.put(new Integer(YAOZU), new Boolean(true));
		nation.put(new Integer(CHAOXIANZU), new Boolean(true));
		nation.put(new Integer(BAIZU), new Boolean(true));
		nation.put(new Integer(HANIZU), new Boolean(true));
		nation.put(new Integer(LIZU), new Boolean(true));
		nation.put(new Integer(HASAKEZU), new Boolean(true));
		nation.put(new Integer(DAIZU), new Boolean(true));
		nation.put(new Integer(SHEZU), new Boolean(true));
		nation.put(new Integer(LISUZU), new Boolean(true));
		nation.put(new Integer(GELAOZU), new Boolean(true));
		nation.put(new Integer(LAHUZU), new Boolean(true));
		nation.put(new Integer(DONGXIANGZU), new Boolean(true));
		nation.put(new Integer(WAZU), new Boolean(true));
		nation.put(new Integer(SHUIZU), new Boolean(true));
		nation.put(new Integer(NAXIZU), new Boolean(true));
		nation.put(new Integer(QIANGZU), new Boolean(true));
		nation.put(new Integer(TUZU), new Boolean(true));
		nation.put(new Integer(XIBOZU), new Boolean(true));
		nation.put(new Integer(MULAOZU), new Boolean(true));
		nation.put(new Integer(KEERKEZIZU), new Boolean(true));
		nation.put(new Integer(DAWOERZU), new Boolean(true));
		nation.put(new Integer(JINGPOZU), new Boolean(true));
		nation.put(new Integer(SALAZU), new Boolean(true));
		nation.put(new Integer(BULANGZU), new Boolean(true));
		nation.put(new Integer(MAONANZU), new Boolean(true));
		nation.put(new Integer(TAJIKEZU), new Boolean(true));
		nation.put(new Integer(PUMIZU), new Boolean(true));
		nation.put(new Integer(ACHANGZU), new Boolean(true));
		nation.put(new Integer(NUZU), new Boolean(true));
		nation.put(new Integer(EWENKEZU), new Boolean(true));
		nation.put(new Integer(JINGZU), new Boolean(true));
		nation.put(new Integer(JINUOZU), new Boolean(true));
		nation.put(new Integer(DEANGZU), new Boolean(true));
		nation.put(new Integer(WUZIBIEKEZU), new Boolean(true));
		nation.put(new Integer(ELUOSIZU), new Boolean(true));
		nation.put(new Integer(YUGUZU), new Boolean(true));
		nation.put(new Integer(BAOANZU), new Boolean(true));
		nation.put(new Integer(MENBAZU), new Boolean(true));
		nation.put(new Integer(ELUNCHUNZU), new Boolean(true));
		nation.put(new Integer(DULONGZU), new Boolean(true));
		nation.put(new Integer(TATAERZU), new Boolean(true));
		nation.put(new Integer(HEZHEZU), new Boolean(true));
		nation.put(new Integer(LUOBAZU), new Boolean(true));
		nation.put(new Integer(GAOSHANZU), new Boolean(true));
		
		nationDict.put(new Integer(HANZU),"汉族");
		nationDict.put(new Integer(ZHUANGZU),"壮族");
		nationDict.put(new Integer(MANZU),"满族");
		nationDict.put(new Integer(HUIZU),"回族");
		nationDict.put(new Integer(MIAOZU),"苗族");
		nationDict.put(new Integer(WEIWUERZU),"维吾尔族");
		nationDict.put(new Integer(YIZU),"彝族");
		nationDict.put(new Integer(TUJIAZU),"土家族");
		nationDict.put(new Integer(MENGGUZU),"蒙古族");
		nationDict.put(new Integer(ZANGZU),"藏族");
		nationDict.put(new Integer(BUYIZU),"布依族");
		nationDict.put(new Integer(DONGZU),"侗族");
		nationDict.put(new Integer(YAOZU),"瑶族");
		nationDict.put(new Integer(CHAOXIANZU),"朝鲜族");
		nationDict.put(new Integer(BAIZU),"白族");
		nationDict.put(new Integer(HANIZU),"哈尼族");
		nationDict.put(new Integer(LIZU),"黎族");
		nationDict.put(new Integer(HASAKEZU),"哈萨克族");
		nationDict.put(new Integer(DAIZU),"傣族");
		nationDict.put(new Integer(SHEZU),"畲族");
		nationDict.put(new Integer(LISUZU),"傈僳族");
		nationDict.put(new Integer(GELAOZU),"仡佬族");
		nationDict.put(new Integer(LAHUZU),"拉祜族");
		nationDict.put(new Integer(DONGXIANGZU),"东乡族");
		nationDict.put(new Integer(WAZU),"佤族");
		nationDict.put(new Integer(SHUIZU),"水族");
		nationDict.put(new Integer(NAXIZU),"纳西族");
		nationDict.put(new Integer(QIANGZU),"羌族");
		nationDict.put(new Integer(TUZU),"土族");
		nationDict.put(new Integer(XIBOZU),"锡伯族");
		nationDict.put(new Integer(MULAOZU),"仫佬族");
		nationDict.put(new Integer(KEERKEZIZU),"柯尔克孜族");
		nationDict.put(new Integer(DAWOERZU),"达斡尔族");
		nationDict.put(new Integer(JINGPOZU),"景颇族");
		nationDict.put(new Integer(SALAZU),"撒拉族");
		nationDict.put(new Integer(BULANGZU),"布朗族");
		nationDict.put(new Integer(MAONANZU),"毛难族");
		nationDict.put(new Integer(TAJIKEZU),"塔吉克族");
		nationDict.put(new Integer(PUMIZU),"普米族");
		nationDict.put(new Integer(ACHANGZU),"阿昌族");
		nationDict.put(new Integer(NUZU),"怒族");
		nationDict.put(new Integer(EWENKEZU),"鄂温克族");
		nationDict.put(new Integer(JINGZU),"京族");
		nationDict.put(new Integer(JINUOZU),"基诺族");
		nationDict.put(new Integer(DEANGZU),"德昂族");
		nationDict.put(new Integer(WUZIBIEKEZU),"乌孜别克族");
		nationDict.put(new Integer(ELUOSIZU),"俄罗斯族");
		nationDict.put(new Integer(YUGUZU),"裕固族");
		nationDict.put(new Integer(BAOANZU),"保安族");
		nationDict.put(new Integer(MENBAZU),"门巴族");
		nationDict.put(new Integer(ELUNCHUNZU),"鄂伦春族");
		nationDict.put(new Integer(DULONGZU),"独龙族");
		nationDict.put(new Integer(TATAERZU),"塔塔尔族");
		nationDict.put(new Integer(HEZHEZU),"赫哲族");
		nationDict.put(new Integer(LUOBAZU),"珞巴族");
		nationDict.put(new Integer(GAOSHANZU),"高山族");
		
	}							
}
